#include "stdafx.h"
#include "2.h"

/* 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int sumEvenFibonacciUpTo(int n) {
	int sum = 0;
	int temp;
	for (int i = 1, j = 2; j < n;) {
		if (j % 2 == 0) sum += j;
		temp = i; 
		i = j;
		j += temp;
	}
	return sum;
}
